FROM ubuntu:14.04

RUN apt-get update \
 && apt-get install -y \
        build-essential \
        cmake \
        libqt4-dev \
        libqt4-dev-bin \
        libusb-1.0-0-dev \
        pkg-config \
        qt4-qmake \
		libqt4-sql-sqlite \
 && apt-get clean
